//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_USER_LOG
    {
        public long LogID { get; set; }
        public string USER_CODE { get; set; }
        public string SYSTEM_CODE { get; set; }
        public Nullable<int> COMP_CODE { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<short> FinYear { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string MODULE_CODE { get; set; }
        public Nullable<byte> OperationId { get; set; }
        public Nullable<long> DataID { get; set; }
        public Nullable<bool> ISSucceed { get; set; }
        public string ErrorNo { get; set; }
        public string ErrorMessage { get; set; }
        public string ExtraData { get; set; }
    }
}
