//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_D_CURRENCY
    {
        public int COMP_CODE { get; set; }
        public string CUR_CODE { get; set; }
        public string DESCA { get; set; }
        public string DESCL { get; set; }
        public Nullable<decimal> FACTOR { get; set; }
        public Nullable<System.DateTime> ACTUAL_DATE { get; set; }
        public string CURSINGLEE { get; set; }
        public string SMALLSINGLEE { get; set; }
        public Nullable<bool> CURMALE { get; set; }
        public Nullable<bool> SMALLCURMALE { get; set; }
        public string CURSINGLEA { get; set; }
        public string CURDOUBLEA { get; set; }
        public string CURPRULARA { get; set; }
        public string SMALLSINGLEA { get; set; }
        public string SMALLDOUBLEA { get; set; }
        public string SMALLPRULARA { get; set; }
    }
}
